import { Product, Category, Order, Review, User, DashboardStats } from '@/types';

export const mockCategories: Category[] = [
  { id: '1', name: 'Vegetables', description: 'Fresh organic vegetables', icon: '🥬' },
  { id: '2', name: 'Fruits', description: 'Seasonal fruits', icon: '🍎' },
  { id: '3', name: 'Grains', description: 'Rice, wheat, and cereals', icon: '🌾' },
  { id: '4', name: 'Dairy', description: 'Milk, cheese, and butter', icon: '🥛' },
  { id: '5', name: 'Pulses', description: 'Lentils and beans', icon: '🫘' },
  { id: '6', name: 'Spices', description: 'Aromatic spices', icon: '🌶️' },
];

export const mockProducts: Product[] = [
  {
    id: '1',
    name: 'Organic Tomatoes',
    description: 'Fresh organic tomatoes grown without pesticides. Perfect for salads and cooking.',
    price: 45,
    unit: 'kg',
    category: 'Vegetables',
    stock: 150,
    farmerId: 'f1',
    farmerName: 'Green Valley Farm',
    images: ['/placeholder.svg'],
    rating: 4.5,
    reviewCount: 23,
    createdAt: '2024-01-15',
  },
  {
    id: '2',
    name: 'Fresh Spinach',
    description: 'Nutrient-rich spinach leaves, freshly harvested every morning.',
    price: 35,
    unit: 'bunch',
    category: 'Vegetables',
    stock: 80,
    farmerId: 'f1',
    farmerName: 'Green Valley Farm',
    images: ['/placeholder.svg'],
    rating: 4.8,
    reviewCount: 45,
    createdAt: '2024-01-14',
  },
  {
    id: '3',
    name: 'Alphonso Mangoes',
    description: 'Premium Alphonso mangoes from Ratnagiri. Sweet and aromatic.',
    price: 450,
    unit: 'dozen',
    category: 'Fruits',
    stock: 50,
    farmerId: 'f2',
    farmerName: 'Sunshine Orchards',
    images: ['/placeholder.svg'],
    rating: 4.9,
    reviewCount: 89,
    createdAt: '2024-01-13',
  },
  {
    id: '4',
    name: 'Basmati Rice',
    description: 'Long grain aromatic basmati rice. Aged for 2 years.',
    price: 180,
    unit: 'kg',
    category: 'Grains',
    stock: 500,
    farmerId: 'f3',
    farmerName: 'Punjab Harvest',
    images: ['/placeholder.svg'],
    rating: 4.6,
    reviewCount: 156,
    createdAt: '2024-01-12',
  },
  {
    id: '5',
    name: 'Farm Fresh Milk',
    description: 'Pure cow milk delivered fresh every morning. No preservatives.',
    price: 60,
    unit: 'litre',
    category: 'Dairy',
    stock: 200,
    farmerId: 'f4',
    farmerName: 'Happy Cows Dairy',
    images: ['/placeholder.svg'],
    rating: 4.7,
    reviewCount: 234,
    createdAt: '2024-01-11',
  },
  {
    id: '6',
    name: 'Red Lentils (Masoor Dal)',
    description: 'High protein red lentils. Quick cooking and nutritious.',
    price: 120,
    unit: 'kg',
    category: 'Pulses',
    stock: 300,
    farmerId: 'f3',
    farmerName: 'Punjab Harvest',
    images: ['/placeholder.svg'],
    rating: 4.4,
    reviewCount: 78,
    createdAt: '2024-01-10',
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    items: [
      { id: '1', productId: '1', productName: 'Organic Tomatoes', quantity: 5, price: 45, unit: 'kg' },
      { id: '2', productId: '2', productName: 'Fresh Spinach', quantity: 3, price: 35, unit: 'bunch' },
    ],
    totalAmount: 330,
    status: 'delivered',
    paymentStatus: 'paid',
    shippingAddress: {
      id: 'a1',
      street: '123 Main Street',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    createdAt: '2024-01-10',
    updatedAt: '2024-01-12',
  },
  {
    id: 'ORD002',
    items: [
      { id: '3', productId: '3', productName: 'Alphonso Mangoes', quantity: 2, price: 450, unit: 'dozen' },
    ],
    totalAmount: 900,
    status: 'processing',
    paymentStatus: 'paid',
    shippingAddress: {
      id: 'a1',
      street: '123 Main Street',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400001',
      country: 'India',
      isDefault: true,
    },
    createdAt: '2024-01-14',
    updatedAt: '2024-01-14',
  },
];

export const mockReviews: Review[] = [
  {
    id: 'r1',
    productId: '1',
    productName: 'Organic Tomatoes',
    userId: 'u1',
    userName: 'Rahul Sharma',
    rating: 5,
    comment: 'Excellent quality tomatoes! Very fresh and tasty.',
    createdAt: '2024-01-12',
  },
  {
    id: 'r2',
    productId: '1',
    productName: 'Organic Tomatoes',
    userId: 'u2',
    userName: 'Priya Patel',
    rating: 4,
    comment: 'Good quality but slightly expensive.',
    createdAt: '2024-01-11',
  },
  {
    id: 'r3',
    productId: '3',
    productName: 'Alphonso Mangoes',
    userId: 'u1',
    userName: 'Rahul Sharma',
    rating: 5,
    comment: 'Best mangoes I have ever had! Worth every rupee.',
    createdAt: '2024-01-13',
  },
];

export const mockUsers: User[] = [
  {
    id: 'u1',
    email: 'buyer@example.com',
    firstName: 'Rahul',
    lastName: 'Sharma',
    phone: '9876543210',
    role: 'buyer',
    createdAt: '2024-01-01',
    isVerified: true,
  },
  {
    id: 'f1',
    email: 'farmer@example.com',
    firstName: 'Kiran',
    lastName: 'Patil',
    phone: '9876543211',
    role: 'farmer',
    createdAt: '2024-01-02',
    isVerified: true,
  },
  {
    id: 'a1',
    email: 'admin@example.com',
    firstName: 'Admin',
    lastName: 'User',
    phone: '9876543212',
    role: 'admin',
    createdAt: '2024-01-01',
    isVerified: true,
  },
];

export const mockDashboardStats: DashboardStats = {
  totalUsers: 1250,
  totalProducts: 458,
  totalOrders: 3420,
  totalRevenue: 1542000,
  pendingOrders: 45,
  activeProducts: 412,
};
